### ISSUE TITLE
Values of the resistors for power measurement

### ISSUE THREAD

**Issue by ErsafanRend** [martin-ger/ESP8266-WiFi-Socket#3]
Do I read the values correctly?
* 8.7 kOhm
* 2.8 kOhm

**Comment by martin-ger** [comment]
It is 8,7 and 2.2 - you need something in the range of some KOhm and with a ration of 4:1 (to devide 5V down to 1V).

**Comment by ErsafanRend** [comment]
Thank you.

**Comment by escoand** [comment]
Why devide down to 1V? According to the referenced PDF document the ADC works with 3.3V. So a ratio of 2:1 would be enough and at the end more accurate.

**Comment by martin-ger** [comment]
Where do you read this? It in Vdd-Mode it measures the supply voltage - then the range is 0-3.3V, but in ADC mode the ESP only works 0-1V. (Page 16 of https://www.espressif.com/sites/default/files/documentation/0a-esp8266ex_datasheet_en.pdf). Some development boards (Wemos D1 mini https://wiki.wemos.cc/products:d1:d1_mini ) have integrated resistors to work in the range 0-3.3V, but the plain ESP has the limitation to 1V.

**Comment by escoand** [comment]
And where can we get the 6.5V?

**Comment by martin-ger** [comment]
Think, I got it from the "+" side of C6. But I as am not at home this week, I cannot verify that.

**Comment by escoand** [comment]
Ok, thanks for the clarification. The 1V thing was not described in detail in this document: http://www.seeedstudio.com/document/word/WT8266-S1%20DataSheet%20V1.0.pdf
