### ISSUE TITLE
Magic Number '185'

### ISSUE THREAD

**Issue by xk4l23** [martin-ger/ESP8266-WiFi-Socket#5]
Hi Martin,
I am currently building your metering power socket and I am trying to understand your sketch. 

So far, I think I got your ideas but one line of code I do not understand well enough. What is the Magic Number 185 in line 116 to calculate ` Ieff = Ueff/185.0;` about? Would you mind explaining this shortly? 

Thank you and regards from Lake Constance,
Björn

**Comment by martin-ger** [comment]
Ueff is in mV and the data sheet of the ACS712 says it has a scale of 185 mV/A.

**Comment by xk4l23** [comment]
Now this makes sense to me, thank you very much.
